### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by janniklasrose** [chebpy/chebpy#12]
There are a few places in the code where some lines are not covered by `nosetests` in TravisCI. This issue can be used to discuss ideas and track progress before a PR is opened.

## General

- [x] `@abstractclassmethod`s can be [excluded from testing](https://stackoverflow.com/a/42204622) - **fixed in  #19**
- [x] Add conditional testing for external packages in `chebpy.core.ffts` and `chebpy.core.plotting` - **fixed in #22**
- [x] Look into [branch coverage](https://coverage.readthedocs.io/en/coverage-5.2.1/branch.html) - this will make % of coverage (look) worse but paint a more accurate picture - **attempted in #24**

## Specific

- [x] `Chebfun.__repr__` and `.__str__` methods don't get tested - call `str(chebfun)` and `repr(chebfun)` - **fixed in #23**
- [ ] `core.algorithms.adaptive` never fails to converge - Needs to be tested with a discontinuous function
- [ ] `core.algorithms.standard_chop` is not tested for `tol>=1` - Add test with subintervals with `hscale > eps`
- [ ] `core.algorithms.vals2coeffs2` and `core.algorithms.coeffs2vals2` are only tested for all real values, never for partially or fully complex values.

**Comment by janniklasrose** [comment]
>  Add conditional testing for external packages in chebpy.core.ffts and chebpy.core.plotting

I actually don't think this is feasible with the current TravisCI setup. Probably the fallback options would need to be excluded from tests or accepted as not covered. Actually, you might not even want to test with numpy's FFT, because in a local `nosetest` without pyfftw I once got a bunch of failed tests - probably due to accuracy issues?

**Comment by markrichardson** [comment]
> I actually don't think this is feasible with the current TravisCI setup. Probably the fallback options would need to be excluded from tests or accepted as not covered. Actually, you might not even want to test with numpy's FFT, because in a local `nosetest` without pyfftw I once got a bunch of failed tests - probably due to accuracy issues?

Yes. Initially Chebpy was built out of numpy ffts but it quickly became apparent that it was difficult to replicate much of the Matlab functionality w.r.t. say degrees of freedom needed to represent canonical functions such as exp(x). Knowing that fftw is native in Matlab I tried it out and it fixed many of these issues.
