### ISSUE TITLE
New tag checklist

### ISSUE THREAD

**Issue by markrichardson** [chebpy/chebpy#56]
When tagging versions we trigger various actions such as conda-forge (and potentially soon PyPi) builds. It makes sense to document the necessary and / or recommended steps (perhaps in the form of a checklist).

**Comment by janniklasrose** [comment]
Yes, good idea! Especially to ensure the same version is deployed to both conda-forge and PyPI. A few notes:

- conda-forge uses the autotick bot that monitors the GitHub release (based on a tag) to ship the new version. 
- For PyPI we (will) use a GitHub Action triggered by a tag to build and push to PyPI. This requires the version in `__init__.py` to be the correct new version.

Thus a new version requires the following:
- [ ] All checks of the most up-to-date commit on `master` should pass. This concerns the merge commit after a PR or something directly pushed to `master` (although PRs are definitely preferred even for us).
- [ ] A new commit is made that increments the `__version__` inside `chebpy/__init__.py` **AND** (optionally) bumps the version in the `launch binder` badge in `README.rst`.
- [ ] That commit is tagged to create a release of that version
- [ ] Ensure a new automatic PR on `chebfun-feedstock` is created
- [ ] Ensure CD workflow for pushing to PyPI happens and succeeds.

**Comment by janniklasrose** [comment]
Voting to keep conda support. Made https://github.com/conda-forge/chebfun-feedstock/pull/22 (@markrichardson if you could review & stamp?) to fix the recipe and bump it to 0.10.0.

**Comment by markrichardson** [comment]
Thanks - and welcome back!

**Comment by markrichardson** [comment]
We should find a way to plumb this in to Rhiza

**Comment by tschm** [comment]
@HarryCampion conda is desired?!
